homepage:
    pattern:  /
    defaults: { _controller: MarkMxSkelBundle:Default:index }

reset_db:
    pattern:  /reset-db
    defaults: { _controller: MarkMxSkelBundle:Default:resetDb }

about:
    pattern:  /about
    defaults: { _controller: MarkMxSkelBundle:Default:about }

_email:
    pattern:  /email
    defaults: { _controller: MarkMxSkelBundle:Default:email }
