homepage:
    pattern:  /
    defaults: { _controller: MarkMxSkelBundle:Default:index }

about:
    pattern:  /about
    defaults: { _controller: MarkMxSkelBundle:Default:about }

_email:
    pattern:  /email
    defaults: { _controller: MarkMxSkelBundle:Default:email }
