homepage:
    pattern:  /
    defaults: { _controller: MarkMxSkelBundle:Default:index }

_default_hello:
    pattern:  /hello/{name}
    defaults: { _controller: MarkMxSkelBundle:Default:hello }

_email:
    pattern:  /email
    defaults: { _controller: MarkMxSkelBundle:Default:email }
